# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               TanGenT RC Log
tagline:             'All the crashes you could imagine'
description:         'Flight log of a first-time FPV experience on the IRC Vortex'
url:                 http://sgregson.github.io/tangent-rc
baseurl:             '/tangent-rc'
paginate:            5
youtube:
  channel:          https://www.youtube.com/channel/UCNcXVpydGn7OEZHpUTV1MFg/
github:
  repo:             http://github.com/sgregson/tangent-rc

# About/contact
author:
  name:              Spencer
  url:               http://sgregson.com
  email:             

# Custom vars
version:             1.0.0
